services:
  database-node-dev:
    image: mongo:5.0
    volumes: 
      - node_db:/data/db
    networks:
      - ducatuscore-node-network-dev
    
  ducatuscore-node-dev:
    build: .
    image: ducatuscore-node
    volumes: 
      - ./packages/ducatuscore-node/src:/ducatuscore/packages/ducatuscore-node/src
    networks:
      - ducatuscore-node-network-dev
    ports:
      - 8100:8100
      - 3001:3000
    environment:
      - DB_HOST=database-node-dev
    env_file: .env
    working_dir: /ducatuscore/packages/ducatuscore-node
    entrypoint: ["npx", "nodemon", "--watch", "./src", "-e", "ts", "--exec", "npm", "start"]

networks:
  ducatuscore-node-network-dev:
    name: ducatuscore-node-network-dev
    driver: bridge

volumes:
  node_db: 