services:
  node-db:
    image: mongo:5.0
    restart: always
    volumes: 
      - /data/node_db:/data/db
    networks:
      - ducatuscore-network 

  dws-db:
    image: mongo:5.0
    restart: always
    volumes: 
      - /data/dws_db:/data/db
    networks:
      - ducatuscore-network
    command: mongod --port 27001
    
  node:
    build: .
    restart: always
    image: ducatuscore-node
    networks:
      - ducatuscore-network
    ports:
      - 8100:8100
      - 3001:3000
    env_file: .env
    working_dir: /ducatuscore/packages/ducatuscore-node
    entrypoint: ["npm", "run", "start"]

  dws:
    build: .
    restart: always
    image: ducatuscore-dws
    links:
      - dws-db
    networks:
      - ducatuscore-network
    env_file: .env
    environment:
      - DB_HOST=dws-db
    working_dir: /ducatuscore/packages/ducatuscore-wallet-service
    entrypoint: "./start.sh"

networks:
  ducatuscore-network:
    name: ducatuscore-node-network
    driver: bridge