version: '3'
services:
  database:
    image: mongo:3.4-jessie
    ports: 
    - 27017:27017
    volumes: 
    - /data/db:/data/db
    
  ducatuscore-node:
    build: .
    image: ducatuscoree-node
    links:
      - database
    ports:
      - 8100:8100
      - 3000:3000
    environment:
      - DB_HOST=database
    env_file: .env